HopeHarbor1/HopeHarbor1/Donor/urls.py
from django.urls import path
from . import views

app_name = 'donor'

urlpatterns = [
    path('', views.donor_entry_request, name='login'),
    path('register/', views.registration, name='register'),

    path('CashPage', views.Cash.as_view(), name='CashPage'),
    path('Cash', views.InsertCashDonation.as_view(), name='Cash'),
    path('CashTracker', views.displayAmountTracker.as_view(), name='CashTracker'),

    path('DiK', views.DiK.as_view(), name='DiK'),
    path('goods', views.InsertGoods.as_view(), name='goods'),
    path('goodstracker', views.displayGoodsTracker.as_view(), name='goodstracker')
]

HopeHarbor1/HopeHarbor1/HopeHarbor1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('donor/', include('Donor.urls')),
    path('AdminStaff/', include('AdminStaff.urls')),
    path('beneficiary/', include('Beneficiary.urls')),  # Include the Beneficiary app's URLs

]

HopeHarbor1/HopeHarbor1/Donor/models.py
from django.db import models
from User.models import User
from AdminStaff.models import AdminStaff
from django.core.validators import MinValueValidator


class Donor(User):
    DONATION_CHOICES = (
        ('cash', 'Cash'),
        ('materials', 'Materials'),
    )
    DonationType = models.CharField(max_length=10, choices=DONATION_CHOICES)
    UserType = models.CharField(
        max_length=12,
        choices=User.USER_TYPES,  # Use choices from User model
        default='donor',  # Set the default to 'donor'
    )




class CashDetails(models.Model):
    CashID = models.BigAutoField(primary_key = True)
    DonorID = models.ForeignKey(Donor, on_delete=models.CASCADE)
    Amount = models.FloatField(default=1.0, validators=[MinValueValidator(1.0)])
    Date = models.DateField(auto_now=True)

    def __str__(self):
        return f"{self.DonorID} - {self.Date}"




class GoodsDetails(models.Model):
    GDID = models.BigAutoField(primary_key = True)
    DonorID = models.ForeignKey(Donor, on_delete=models.CASCADE)
    DateofDonation = models.DateField(auto_now=True)

    def __str__(self):
        return f"{self.DateofDonation}"


class Currency(models.Model):
    CurrencyID = models.BigAutoField(primary_key=True)
    CashID = models.ForeignKey(CashDetails, on_delete=models.CASCADE)
    CURRENCY_CHOICES = (
        ('USD', 'US Dollar'),
        ('EUR', 'Euro'),
        ('JPY', 'Japanese Yen'),
        ('GBP', 'British Pound Sterling'),
        ('CAD', 'Canadian Dollar'),
        ('AUD', 'Australian Dollar'),
        ('CHF', 'Swiss Franc'),
        ('CNY', 'Chinese Yuan'),
        ('INR', 'Indian Rupee'),
        ('RUB', 'Russian Ruble'),
        ('ZAR', 'South African Rand'),
        ('AED', 'United Arab Emirates Dirham'),
        ('SGD', 'Singapore Dollar'),
        ('NZD', 'New Zealand Dollar'),
        ('HKD', 'Hong Kong Dollar'),
        ('SEK', 'Swedish Krona'),
        ('NOK', 'Norwegian Krone'),
        ('DKK', 'Danish Krone'),
        ('KRW', 'South Korean Won'),
        ('BRL', 'Brazilian Real'),
        ('MXN', 'Mexican Peso'),
        ('ARS', 'Argentine Peso'),
        ('TRY', 'Turkish Lira'),
        ('EGP', 'Egyptian Pound'),
        ('PHP', 'Philippine Peso'),
        # Add more currencies as needed
    )
    CurrencyType = models.CharField(max_length=3, choices=CURRENCY_CHOICES, default='PHP')

    def __str__(self):
        return self.get_CurrencyType_display()


class DIK(models.Model):
    DikID = models.BigAutoField(primary_key=True)
    GDID = models.ForeignKey(GoodsDetails, on_delete=models.CASCADE)

    # Use the same tuple of choices as in the Beneficiary model
    NEEDS_CHOICES = (
        ('food', 'Food'),
        ('clothing', 'Clothing'),
        ('shelter', 'Shelter'),
        ('education', 'Education'),
        ('medical', 'Medical'),
        ('utilities', 'Utilities'),
        ('transportation', 'Transportation'),
        ('employment', 'Employment'),
        ('other', 'Other'),
        # Add more charity needs options here
    )

    DikType = models.CharField(max_length=50, choices=NEEDS_CHOICES, default='food')

    def __str__(self):
        return f"Date of Donation: {self.GDID} - Type: {self.DikType}"


class Amount_Tracker(models.Model):
    Amount_TrackerID = models.BigAutoField(primary_key = True)
    CurrencyID = models.ForeignKey(Currency, on_delete=models.CASCADE)
    AdminID = models.ForeignKey(AdminStaff, on_delete=models.CASCADE)
    Amount = models.FloatField(default=1.0, validators=[MinValueValidator(1)])



class Goods_Tracker(models.Model):
    GoodsTrackerID = models.BigAutoField(primary_key = True)
    DonationInKind = models.ForeignKey(DIK, on_delete=models.CASCADE)
    AdminID = models.ForeignKey(AdminStaff, on_delete=models.CASCADE)
    Quantity = models.IntegerField(default=0, validators=[MinValueValidator(1)])


# Rowen and Gian

HopeHarbor1/HopeHarbor1/Donor/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from .models import Donor


class Donor_Login_Form(forms.ModelForm):
    Username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Enter Username'}))
    Password = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Enter Password'}))

    class Meta:
        model = Donor
        fields = ['Username', 'Password']


class Donor_Registration_Form(forms.ModelForm):
    types = [
        ('cash', 'Cash'),
        ('materials', 'Materials'),
    ]
    EmailAddress = forms.EmailField(
        required=True,
        label="Email",
        widget=forms.EmailInput(attrs={'id': 'email'})
)
    Username = forms.CharField(required=True)
    Password = forms.PasswordInput()
    UserType = forms.CharField(widget=forms.HiddenInput, initial='donor')
    #DonationType = forms.ChoiceField(choices=types, widget=forms.Select(attrs={'id': 'select'}), label="Donation Type")
    FirstName = forms.CharField(
        label="First Name"
    )
    LastName = forms.CharField(
        label="Last Name"
    )

    class Meta:
        model = Donor
        fields = ['Username', 'EmailAddress', 'Password', 'FirstName', 'LastName', 'UserType']

HopeHarbor1/HopeHarbor1/Donor/views.py
from datetime import date, timezone

from django.core.exceptions import ValidationError, ObjectDoesNotExist
from django.db import connection
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.views import View
from .models import Donor
from .forms import Donor_Login_Form, Donor_Registration_Form
# Create your views here.

def index(request):
    return render(request, 'index.html')

class Cash(View):
    template='index.html'

    def get(self, request):
        uname = request.session['username']
        return render(request, self.template, {'Username': uname})

    def post(self, request):
        uname = request.session['username']
        request.session['username'] = uname
        return redirect('/cash')

class DiK(View):
    template='index.html'

    def get(self, request):
        uname = request.session['username']
        return render(request, self.template, {'Username': uname})

    def post(self, request):
        uname = request.session['username']
        request.session['username'] = uname
        return redirect('/goods')



def donor_entry_request(request):
    if request.method == "POST":
        form = Donor_Login_Form(request.POST)
        if form.is_valid():
            Username = form.cleaned_data.get('Username')
            Password = form.cleaned_data.get('Password')

            condition1 = Donor.objects.filter(Username=Username)
            condition2 = Donor.objects.filter(Password=Password)
            if condition1 and condition2:
                request.session['username'] = Username
                return HttpResponseRedirect('/donor/CashPage')
            elif condition1 and Password != condition2:
                raise ValidationError("Incorrect Password!")
            else:
                raise ValidationError("No user found!")
    else:
        form = Donor_Login_Form()

    return render(request, 'login.html', {'form' : form})

def registration(request):
    if request.method == 'POST':
        form = Donor_Registration_Form(request.POST)
        if form.is_valid():
            Username = form.cleaned_data.get('Username')

            condition1 = Donor.objects.filter(Username=Username)
            if condition1:
                raise ValidationError("User already exists!")
            else:
                form.save()
                return HttpResponse("Welcome Donor")
    else:
        form = Donor_Registration_Form()

    return render(request, 'registration.html', {'form':form})

class InsertGoods(View):
    template = 'DIKpage.html'

    def get(self, request):
        return render(request, self.template)

    def post(self, request):
        quantity = request.POST['quantity']
        label = request.POST['label']
        perishable = 'perishable' in request.POST
        expiry = request.POST['expiry']
        cursor = connection.cursor()
        username = request.session['username']
        args = [perishable, expiry or None, label, username, quantity]
        cursor.callproc('InsertGoodsDonation', args)
        result = cursor.fetchall()
        cursor.close()
        print(result)
        msg = request.session['username']
        request.session['username'] = username
        return redirect('/goodstracker')



class displayGoodsTracker(View):
    template = 'DonationTracker.html'

    def get(self, request):
        donor_username = request.session['username']
        cursor = connection.cursor()
        cursor.callproc('DisplayGoodsTracker', [donor_username])
        results = cursor.fetchall()
        cursor.close()
        print(results)
        return render(request, self.template, {'results': results})

class InsertCashDonation(View):
    template = 'Cash.html'

    def get(self, request):
        return render(request, self.template)

    def post(self, request):
        Amount = request.POST['amount']
        Date = date.today()
        Currency = request.POST['currency']
        AdminID = 1
        Username = request.session['username']

        cursor = connection.cursor()
        cursor.execute('SELECT UserID FROM donor_donor WHERE Username = %s', [Username])
        DonorID = cursor.fetchone()[0]
        cursor.close()

        cursor = connection.cursor()
        args = [Amount, Date, DonorID, Currency, AdminID]
        cursor.callproc('MakeDonation', args)
        result = cursor.fetchall()
        cursor.close()
        print(result)
        msg = request.session['username']
        request.session['username'] = Username
        return redirect('/donor/CashTracker')



class displayAmountTracker(View):
    template = 'Cash_Donations.html'

    def get(self, request):
        username = request.session['username']
        cursor = connection.cursor()
        cursor.callproc('DisplayCashTracker', [username])
        results = cursor.fetchall()
        cursor.close()
        return render(request, self.template, {'results': results})

HopeHarbor1/HopeHarbor1/Donor/templates/DIKpage.html
{% load static %}
<html lang="en" xmlns:margin-bottom="http://www.w3.org/1999/xhtml">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Home - Brand</title>
    <link rel="stylesheet" href="{%static 'assets/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{%static 'assets/css/Archivo.css' %}">
    <link rel="stylesheet" href="{%static 'assets/css/Montserrat.css' %}">
    <link rel="stylesheet" href="{%static 'assets/fonts/simple-line-icons.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.11.1/baguetteBox.min.css">
    <link rel="stylesheet" href="{%static 'assets/css/vanilla-zoom.min.css' %}">
    <style>
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
  * {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
  }
  body {
    font-family: 'Inter', sans-serif;
  }
  .formbold-mb-3 {
    margin-bottom: 15px;
  }
  .formbold-relative {
    position: relative;
  }
  .formbold-opacity-0 {
    opacity: 0;
  }
  .formbold-stroke-current {
    stroke: currentColor;
  }
  #supportCheckbox:checked ~ div span {
    opacity: 1;
  }

  .formbold-main-wrapper {
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 48px;
  }

  .formbold-form-wrapper {
    margin: 0 auto;
    max-width: 570px;
    width: 100%;
    background: white;
    padding: 40px;
  }

  .formbold-img {
    margin-bottom: 45px;
  }

  .formbold-form-title {
    margin-bottom: 30px;
  }
  .formbold-form-title h2 {
    font-weight: 600;
    font-size: 28px;
    line-height: 34px;
    color: #07074d;
  }
  .formbold-form-title p {
    font-size: 16px;
    line-height: 24px;
    color: #536387;
    margin-top: 12px;
  }

  .formbold-input-flex {
    display: flex;
    gap: 20px;
    margin-bottom: 15px;
  }
  .formbold-input-flex > div {
    width: 50%;
  }
  .formbold-form-input {
    text-align: left;
    width: 100%;
    padding: 13px 22px;
    border-radius: 5px;
    border: 1px solid #dde3ec;
    background: #ffffff;
    font-weight: 500;
    font-size: 16px;
    color: #536387;
    outline: none;
    resize: none;
  }

  .formbold-form-input-int {
    text-align: center;
    width: 20%;
    padding: 13px;
    border-radius: 5px;
    border: 1px solid #dde3ec;
    background: #ffffff;
    font-weight: 500;
    font-size: 16px;
    color: #536387;
    outline: none;
    resize: none;
  }

  .formbold-form-input-int:focus {
    border-color: #0D6EFD;
    box-shadow: 0px 3px 8px rgba(0, 0, 0, 0.05);
  }

  .formbold-form-input:focus {
    border-color: #0D6EFD;
    box-shadow: 0px 3px 8px rgba(0, 0, 0, 0.05);
  }
  .formbold-form-label {
    color: #536387;
    font-size: 14px;
    line-height: 24px;
    display: block;
    margin-bottom: 10px;
  }

  .formbold-checkbox-label {
    display: flex;
    cursor: pointer;
    user-select: none;
    font-size: 16px;
    line-height: 24px;
    color: #536387;
  }
  .formbold-checkbox-label a {
    margin-left: 5px;
    color: #6a64f1;
  }
  .formbold-input-checkbox {
    position: absolute;
    width: 1px;
    height: 1px;
    padding: 0;
    margin: -1px;
    overflow: hidden;
    clip: rect(0, 0, 0, 0);
    white-space: nowrap;
    border-width: 0;
  }
  .formbold-checkbox-inner {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 20px;
    height: 20px;
    margin-right: 16px;
    margin-top: 2px;
    border: 0.7px solid #dde3ec;
    border-radius: 3px;
  }

  .formbold-btn {
    appearance: button;
  backface-visibility: hidden;
  background-color: #0D6EFD;
  border-radius: 6px;
  border-width: 0;
  box-shadow: rgba(50, 50, 93, .1) 0 0 0 1px inset,rgba(50, 50, 93, .1) 0 2px 5px 0,rgba(0, 0, 0, .07) 0 1px 1px 0;
  box-sizing: border-box;
  color: #fff;
  cursor: pointer;
  font-family: -apple-system,system-ui,"Segoe UI",Roboto,"Helvetica Neue",Ubuntu,sans-serif;
  font-size: 100%;
  height: 44px;
  line-height: 1.15;
  margin: 12px 0 0;
  outline: none;
  overflow: hidden;
  padding: 0 25px;
  position: relative;
  text-align: center;
  text-transform: none;
  transform: translateZ(0);
  transition: all .2s,box-shadow .08s ease-in;
  user-select: none;
  -webkit-user-select: none;
  touch-action: manipulation;
  width: 100%;
  }
  .formbold-btn:hover {
    box-shadow: 0px 3px 8px rgba(0, 0, 0, 0.05);
  }
    </style>
</head>

<body>

<nav class="navbar navbar-light navbar-expand-lg fixed-top clean-navbar" style="background: #002156;">
        <div class="container"><a class="navbar-brand logo" href="#" style="font-family: Archivo, sans-serif;color: rgba(255,255,255,0.9);font-weight: bold;">HopeHarbor</a><button data-bs-toggle="collapse" class="navbar-toggler" data-bs-target="#navcol-1"><span class="visually-hidden">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navcol-1">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item"><a class="nav-link active" href="{% url 'donor:DiK' %}" style="color: rgba(255,255,255,0.9);">Home</a></li>
                    <li class="nav-item"><a class="nav-link" href="pricing.html" style="color: rgb(255,255,255);">donate</a></li>
                    <li class="nav-item"><a class="nav-link" href="about-us.html" style="color: rgb(255,255,255);">About Us</a></li>
<!--                    <li class="nav-item"><a class="nav-link" href="contact-us.html" style="color: rgb(255,255,255);">register</a></li>-->
                </ul>
            </div>
        </div>
    </nav>

<main class="page landing-page">

<!--    <section class="clean-block clean-hero" style="color: rgba(9,162,255,0);background: url(&quot;{% static 'assets/img/tech/9548273.jpg' %}&quot;);">-->
<!--            <div class="text">-->
<!--                <h2 style="font-family: Archivo, sans-serif;font-size: 80px;font-weight: bold;">HopeHarbor</h2>-->
<!--                <p style="font-family: Archivo, sans-serif;">We're here to support you on your journey to a brighter future. Explore the resources and assistance we offer, and know that we're here for you every step of the way. Together, we'll navigate toward a better tomorrow.</p><button class="btn btn-outline-light btn-lg" type="button">Learn More</button>-->
<!--            </div>-->
<!--    </section>-->

<!--    <section class="clean-block clean-info dark">-->
<!--            <div class="container">-->
<!--                <div class="block-heading">-->
<!--                    <h2 class="text-info" style="font-family: Archivo, sans-serif;">Donation in Kind Form</h2>-->
<!--                </div>-->
<!--            </div>-->
<!--    </section>-->

  <div class="formbold-main-wrapper">
  <!-- Author: FormBold Team -->
  <!-- Learn More: https://formbold.com -->
  <div class="formbold-form-wrapper">

    <form method="post">
        {% csrf_token %}
      <div class="formbold-form-title">
        <h2 class="">Donation in Kind</h2>
        <p>
          Please enter the quantity and name of the item that you would like to
          donate.
        </p>
      </div>

      <div>
          <label for="firstname" class="formbold-form-label">
            Quantity
          </label>
          <input
            type="number"
            name="quantity"
            id="firstname"
            class="formbold-form-input-int"
          />
      </div>

      <br>

      <div class="formbold-mb-3">
        <label for="address" class="formbold-form-label">
          Label
        </label>
        <input
          type="text"
          name="label"
          id="address"
          class="formbold-form-input"
        />
      </div>

      <br>

        <div>
            <input
              type="checkbox"
              id="isitperishable"
              name="perishable"
            />
      <label for="isitperishable">Is it perishable?<label>
        </div>

      <br>
        <br>

      <div class="formbold-mb-3">
        <label for="expiry" class="formbold-form-label">
          Expiration Date
        </label>
        <input
          type="date"
          name="expiry"
          id="expiry"
          class="formbold-form-input"
        />
      </div>

      <button class="formbold-btn">Donate</button>
    </form>
      {{ msg }}
  </div>
</div>

     </main>

<footer class="page-footer dark">
        <div class="container">
            <div class="row">
                <div class="col-sm-3">
                    <h5>Get started</h5>
                    <ul>
                        <li><a href="#">Home</a></li>
                        <li><a href="#">Sign up</a></li>
                        <li><a href="#">Downloads</a></li>
                    </ul>
                </div>
                <div class="col-sm-3">
                    <h5>About us</h5>
                    <ul>
                        <li><a href="#">Company Information</a></li>
                        <li><a href="#">Contact us</a></li>
                        <li><a href="#">Reviews</a></li>
                    </ul>
                </div>
                <div class="col-sm-3">
                    <h5>Support</h5>
                    <ul>
                        <li><a href="#">FAQ</a></li>
                        <li><a href="#">Help desk</a></li>
                        <li><a href="#">Forums</a></li>
                    </ul>
                </div>
                <div class="col-sm-3">
                    <h5>Legal</h5>
                    <ul>
                        <li><a href="#">Terms of Service</a></li>
                        <li><a href="#">Terms of Use</a></li>
                        <li><a href="#">Privacy Policy</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="footer-copyright"></div>
    </footer><!-- End: Footer Dark -->
    <script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.11.1/baguetteBox.min.js"></script>
    <script src="{% static 'assets/js/vanilla-zoom.js' %}"></script>
    <script src="{% static 'assets/js/theme.js' %}"></script>

</body>
</html>

HopeHarbor1/HopeHarbor1/Donor/templates/login.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CSS Login Page Template - W3jar.Com</title>
    <link href="{% static 'style.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'style-with-prefix.css' %}">
    <style>
        .srouce{
            text-align: center;
            color: #ffffff;
            padding: 10px;
        }
    </style>
</head>
<body>

    <div class="main-container">
        <div class="form-container">

            <div class="srouce"><a title="Learn How to create Beautiful HTML & CSS login page template" href="https://www.w3jar.com/beautiful-html-css-login-page-template/"></a></div>

            <div class="form-body">
                <h2 class="title">Log in with</h2>
                <div class="social-login">
                    <ul>
                        <li class="google"><a href="#">Google</a></li>
                        <li class="fb"><a href="#">Facebook</a></li>
                    </ul>
                </div><!-- SOCIAL LOGIN -->

                <div class="_or">or</div>

                <form method="post" class="the-form">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" value="Log In">
                </form>

            </div><!-- FORM BODY-->

            <div class="form-footer">
                <div>
                    <span>Don't have an account?</span> <a href="{% url 'donor:register' %}">Sign Up</a>
                </div>
            </div><!-- FORM FOOTER -->

        </div><!-- FORM CONTAINER -->
    </div>

</body>
</html>

HopeHarbor1/HopeHarbor1/Donor/templates/registration.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CSS Login Page Template - W3jar.Com</title>
    <link href="{% static 'style.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'style-with-prefix.css' %}">
    <style>
        .srouce{
            text-align: center;
            color: #ffffff;
            padding: 10px;
        }
    </style>
</head>
<body>

    <div class="main-container">
        <div class="form-container">

            <div class="srouce"><a title="Learn How to create Beautiful HTML & CSS login page template" href="https://www.w3jar.com/beautiful-html-css-login-page-template/"></a></div>

            <div class="form-body">
                <h2 class="title">Registration</h2>
                <!-- SOCIAL LOGIN -->

                <div class="_or"></div>

                <form method="post" class="the-form">
                    {% csrf_token %}
                    {{form.as_p}}
                    <input type="submit" value="Sign Up">

                </form>

            </div><!-- FORM BODY-->

            <div class="form-footer">
                <div>
                    <span>Already have an account?</span> <a href="{% url 'donor:login' %}">Sign In</a>
                </div>
            </div><!-- FORM FOOTER -->

        </div><!-- FORM CONTAINER -->
    </div>

</body>
</html>